### ISSUE TITLE
Could you please provide your code? I think your code is very good and I would like to refer to the method you use

### ISSUE THREAD

**Issue by WangZhi-wz** [mlyg/Focus-U-Net#1]
Could you please provide your code? I think your code is very good and I would like to refer to the method you use

**Comment by mlyg** [comment]
Many thanks for your interest. Please bear with me and I will update you once I have the code prepared.

**Comment by Viibon** [comment]
hi，i am very interested in your FocusGate module，i wanna refer the method of this paper，but I just can code some simple module such as short skip or channel and spatial attention, so may I ask you how soon could you update your code especially the FocusGate module, if you are not convenient to update your code, could you contact me by email and share your code or give me some advice? My email is viibon@outlook.com. Thank u very much!

**Comment by mlyg** [comment]
I aim to have at code out over the next few days. If you need any advice in the meantime I am more than happy to help and you can contact me directly at: mjyy2@cam.ac.uk. 

Please bear in mind that the FocusGate is written using the Tensorflow/Keras libraries and I do not have it implemented in PyTorch, but again I can try to help if that is the library that you are using.

**Comment by mlyg** [comment]
Thanks for your patience - I have uploaded the code for the Focus Gate and also an interactive notebook where you can test out the performance and visualise attention coefficients against the original U-Net.
